<a href="https://colab.research.google.com/github/GustaFTW/TensorFlow-ZTM/blob/main/section0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow.
* Introduction
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (a wat to speed up your regular Python Functions)
* Using GPUs with TensorFlow
* Exercises


###**Introduction to Tensors**

In [ ]:
# Import TensorFlow
import numpy as np
import tensorflow as tf
print(tf.__version__)

2.9.2


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the numbers of dimensions of a tensor
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[4., 9.],
                              [3, 2.],
                              [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[4., 9.],
       [3., 2.],
       [8., 9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

### What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimension array of numbers
* Tensor: an n-dimensional array of number 

In [ ]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try change of the elements in our changeable tensor
# changeable_tensor[0] = 12

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(232)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([232,   7], dtype=int32)>

In [ ]:
# Let's try change our unchangeable tensor
# unchangeable_tensor[0].assign(232)
# unchangeable_tensor

### Creating random tensor

Random tensor are tensors of some arbitrary size which contain random numbers. 

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape = (4, 3))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (4, 3))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 ],
        [-0.57166284,  0.1480774 , -0.23362993]], dtype=float32)>,
 <tf.Tensor: shape=(4, 3), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 ],
        [-0.57166284,  0.1480774 , -0.23362993]], dtype=float32)>,
 <tf.Tensor: shape=(4, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)

Shuffle the order of elements in a tensor

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order
# doesn't affect learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 5],
                            [2, 5]])
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  5]], dtype=int32)>

In [ ]:
# Shuffle our non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  5],
       [ 2,  5]], dtype=int32)>

**Exercise**


In [ ]:
# Create 5 random tensors and shuffle them
random = tf.random.Generator.from_seed(69)
random1 = random.normal(shape=(3, 2))
tf.random.shuffle(random1)
random2 = random.normal(shape=(3,2))
tf.random.shuffle(random2)
random3 = random.normal(shape=(3,2))
tf.random.shuffle(random3)
random4 = random.normal(shape=(3,2))
tf.random.shuffle(random4)
random5 = random.normal(shape=(3,2))
tf.random.shuffle(random5)
random1, random2, random3, random4, random5

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.29164317,  1.4531525 ],
        [-0.8223833 , -1.3446563 ],
        [-0.7183838 , -0.20373915]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.6094785 , -0.20813271],
        [-1.8241427 ,  0.82461065],
        [-0.17353141,  0.52762544]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 2.0006597 , -0.52585185],
        [ 0.23797339, -0.06052312],
        [ 0.0166028 ,  0.42335185]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.6806577 , -0.8685411 ],
        [ 1.3559858 ,  0.52442944],
        [-0.41015142, -0.43921748]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.41136   , -1.0980463 ],
        [-0.7666738 , -0.08916527],
        [ 0.6265605 , -1.1105936 ]], dtype=float32)>)

In [ ]:
# If we want our shuffled tensors to be in the same order, both the global lvl seed
# and the operational level seed must be determined
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  5],
       [ 2,  5]], dtype=int32)>

### Other ways to make tensors


In [ ]:
# Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create a tensor of all zeros
tf.zeros([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

### NumPy arrays into tensors
The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing).


In [ ]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(3, 2, 4))
A


<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting information from tensors

When dealing with tensor you probably want to be aware of the following attributes: 
* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
# Create a rank 4 tensor (4 dimensions)

rank_4_tensor = tf.ones(shape=[2, 3, 4, 5])
rank_4_tensor


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of our tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor).numpy())


Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in our tensor:  120


### Indexing tensor

Tensor can be indexed just like Python lists.

In [ ]:
# Get the firts 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[1:, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[1., 1., 1., 1., 1.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                            [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor[..., -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis = -1) # "-1" expands the final axis 

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Expand the 0-axis
tf.expand_dims(rank_2_tensor, axis = 0) 

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating tensor (tensor operations)

**Basic operations**

`+`, `-`, `*`, `/`

In [ ]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# Division 
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [ ]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
# We can use the tensorflow built-in function too 
# (it gets speed up through the GPU, so it's faster)
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

### **Matrix multiplication**

In machine learning, Is one of the most common operations 

There are two rules our tensors (or matrices) need to fullfil if we're going to matrix multiply them:
1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions

In [ ]:
# Matrix multiplication in tensorflow
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Matrix multiplication with Python operator "@"
tensor @ tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor.shape

TensorShape([2, 2])

In [ ]:
# Create a tensor (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Try to matrix multiply tensors of same shape
# tf.matmul(X, Y)

In [ ]:
# Fixing the error 

# Create a tensor (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
# Create another (2, 3) tensor
Y = tf.constant([[7, 8, 9],
                 [10, 11, 12]])
# Inner dimensions now match
tf.matmul(X, Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

**The dot product**

Matrix multiplication is also referred to as the dot product.

You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`

In [ ]:
Y = tf.reshape(Y, [3, 2])
X, Y


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul (X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Check the values of Y, reshape Y and transposed Y
print("Normal Y: ")
print(Y, "\n")

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Transposed Y: ")
print(tf.transpose(Y))


Normal Y: 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Transposed Y: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Generally, when perfoming matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to satisfy the matrix rules


### Changing the dataype of a tensor

In [ ]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [ ]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [ ]:
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype = tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [ ]:
# Change from int32 to float32
E = tf.cast(C, dtype = tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [ ]:
E_float16 = tf.cast(E, dtype = tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [ ]:
# Get the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation:

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
# Tensor 1
X = tf.constant(np.random.randint(0, 101, size = 50))
X
# Tensor 2
Y = tf.constant([[5, 6],
                 [7, 8]])

# Getting the minimum
tf.reduce_min(X)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
# Getting the maximum 
tf.reduce_max(X)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
# Getting the mean
tf.reduce_mean(X)

<tf.Tensor: shape=(), dtype=int64, numpy=45>

In [ ]:
# Getting the sum
tf.reduce_sum(X)

<tf.Tensor: shape=(), dtype=int64, numpy=2283>

In [ ]:
# Getting the variance
tf.math.reduce_variance(tf.cast(X, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=786.90436>

In [ ]:
# Getting the standard deviation
tf.math.reduce_std(tf.cast(X, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.051815>

In [ ]:
tf.math.reduce_std(E)

<tf.Tensor: shape=(), dtype=float32, numpy=1.5>

### Find the positional maximum and minimum ###

In [ ]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find the positional maximum (argmax)
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Index on our largest values position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape =(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 <tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
 array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
            0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
            0.3103881 , 0.7223358 , 0.133187

### One-hot enconding tensor

In [ ]:
# Create a list of indices
some_list = [0, 1, 2, 3] # could be red, green, blue, purple

# One hot encode our list of indices
tf.one_hot(some_list, 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, 4, on_value="on", off_value="off")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'on', b'off', b'off', b'off'],
       [b'off', b'on', b'off', b'off'],
       [b'off', b'off', b'on', b'off'],
       [b'off', b'off', b'off', b'on']], dtype=object)>

### Squaring, log, square root

In [ ]:
# Create a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Find the squareroot (method require a non int type of data)
tf.sqrt(tf.cast(H, tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
# Find the log
tf.math.log(tf.cast(H, tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

TensorFlow interacts beautifully with NumPy arrays.
***Note:*** One of the main differents between a NumPy array and a Tensor is that a TensorFlow tensor can be run on a GPU or TPU (for faster numerical processing).

In [ ]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Convert our tensor back to a NumPy array
np.array(J)

array([ 3.,  7., 10.])

In [ ]:
# Convert tensor J to a NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [ ]:
tf.config.list_physical_devices("GPU")

[]

In [ ]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



> ***Note:*** If you have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible

### Extra-curriculum exercises

In [ ]:
# 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant()
scalar = tf.constant(1)
vector = tf.constant([1, 2])
matrix = tf.constant([[1, 2],
                      [3, 4]])
tensor = tf.constant([[1, 2],
                      [3, 4],
                      [5, 6]])
scalar, vector, matrix, tensor

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>)

In [ ]:
# 2. Find the shape, rank and size of the tensors you created in 1.
print(f"shape: {tf.shape(tensor)}")
print(f"size: {tf.size(tensor)}")
print(f"rank: {tf.rank(tensor)}")

shape: [3 2]
size: 6
rank: 2


In [ ]:
# 3. Create two tensors containing random values between 0 and 1 with shape [5, 100]
tensor1 = tf.random.uniform(shape=[5, 100], minval=0, maxval=1)
print(tensor1)
tensor2 = tf.random.uniform(shape=[5, 100], minval=0, maxval=1)
print(tensor2)





tf.Tensor(
[[6.87891245e-01 4.84478831e-01 9.30994391e-01 2.52187014e-01
  7.31153965e-01 8.92568231e-01 9.46748257e-01 7.49334097e-01
  3.49256277e-01 5.47182560e-01 2.61603951e-01 6.97343230e-01
  1.19625807e-01 5.34843445e-01 7.14896798e-01 8.75017762e-01
  3.39674950e-01 1.73776269e-01 4.41852093e-01 9.00826097e-01
  1.38038635e-01 1.22179747e-01 5.75449109e-01 9.41718102e-01
  9.18658495e-01 5.97084761e-01 6.10948205e-01 8.20862651e-01
  8.32697868e-01 8.91584873e-01 1.37722492e-02 4.98074651e-01
  5.75036645e-01 6.85619473e-01 7.59727836e-01 9.08944011e-01
  4.09002185e-01 8.76515388e-01 5.38900256e-01 4.27330971e-01
  4.01172996e-01 6.66232467e-01 1.63480639e-01 1.82202458e-01
  9.70401764e-01 6.13973141e-02 5.30347466e-01 9.86999393e-01
  4.74694490e-01 8.64675403e-01 2.03010678e-01 1.14484549e-01
  3.51002455e-01 6.82271838e-01 1.81088686e-01 8.16348076e-01
  6.56516552e-01 9.25825596e-01 2.39171505e-01 8.36595774e-01
  4.76527214e-02 8.00715685e-01 8.29926729e-01 1.43283725e-

In [ ]:
# 4. Multiply the two tensors you created in 3 using matrix multiplication.
tensor2 = tf.reshape(tensor2, shape=(100, 5))
tf.matmul(tensor1, tensor2)


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[30.307102, 27.889404, 25.027458, 29.813896, 25.67709 ],
       [26.830631, 26.173355, 24.788078, 27.239925, 24.331419],
       [28.694496, 26.392677, 22.148926, 27.540264, 24.473476],
       [25.872168, 24.174068, 23.73175 , 27.332026, 23.81073 ],
       [24.80532 , 25.899158, 24.123388, 27.099855, 23.368618]],
      dtype=float32)>

In [ ]:
# 5. Multiply the two tensors you created in 3 using dot product.
tf.tensordot(tensor1, tensor2, 1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[30.307102, 27.889404, 25.027458, 29.813896, 25.67709 ],
       [26.830631, 26.173355, 24.788078, 27.239925, 24.331419],
       [28.694496, 26.392677, 22.148926, 27.540264, 24.473476],
       [25.872168, 24.174068, 23.73175 , 27.332026, 23.81073 ],
       [24.80532 , 25.899158, 24.123388, 27.099855, 23.368618]],
      dtype=float32)>

In [ ]:
# 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3]
tensor1 = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1)
tensor1

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[7.4023080e-01, 3.3938193e-01, 5.6925058e-01],
        [4.4811392e-01, 2.9285502e-01, 4.2600560e-01],
        [6.2890387e-01, 6.9106102e-01, 3.0925727e-01],
        ...,
        [9.1063976e-04, 6.9863999e-01, 1.7180574e-01],
        [6.7542684e-01, 8.3492923e-01, 3.9038682e-01],
        [2.3664141e-01, 6.2239432e-01, 1.0117912e-01]],

       [[9.7064960e-01, 5.4594779e-01, 7.6819682e-01],
        [2.6893330e-01, 2.6959443e-01, 2.8982997e-01],
        [2.9215467e-01, 1.7108858e-01, 6.5597153e-01],
        ...,
        [9.5621395e-01, 5.4591870e-01, 5.3843534e-01],
        [9.8861516e-01, 1.5786767e-01, 6.1375093e-01],
        [7.2668612e-01, 6.1637163e-03, 1.6534305e-01]],

       [[6.4095867e-01, 7.6697862e-01, 3.0138540e-01],
        [1.5474892e-01, 1.7183411e-01, 2.7192724e-01],
        [3.1211805e-01, 6.1451709e-01, 4.3001354e-01],
        ...,
        [8.4168065e-01, 5.0247252e-01, 2.8834987e-01],
        [3.3173549e-01

In [ ]:
# 7. Find the min and max values of the tensor you created in 6 along the first axis.
print(tf.reduce_min(tensor1, 1))
print(tf.reduce_max(tensor1, 1))

tf.Tensor(
[[9.10639763e-04 6.54578209e-04 3.16035748e-03]
 [8.35013390e-03 1.16729736e-03 1.09343529e-02]
 [3.31878662e-03 1.99556351e-04 1.74641609e-03]
 [4.14729118e-03 3.09562683e-03 1.42467022e-03]
 [7.07781315e-03 2.19345093e-05 5.38456440e-03]
 [5.42986393e-03 2.22206116e-04 7.89272785e-03]
 [5.10823727e-03 6.99520111e-04 2.83420086e-03]
 [1.07038021e-03 2.34723091e-04 7.52758980e-03]
 [1.66893005e-03 9.80639458e-03 2.58088112e-03]
 [2.11358070e-04 1.70731544e-03 1.35517120e-03]
 [8.23807716e-03 5.60522079e-04 8.54849815e-03]
 [1.17849112e-02 1.96158886e-03 4.79292870e-03]
 [5.68139553e-03 6.36565685e-03 9.84787941e-04]
 [2.73835659e-03 4.16231155e-03 4.78243828e-03]
 [3.51417065e-03 3.18551064e-03 6.12378120e-04]
 [3.91662121e-03 4.14466858e-03 3.65471840e-03]
 [1.91652775e-03 3.83377075e-04 8.68165493e-03]
 [3.22473049e-03 7.75098801e-04 1.14122629e-02]
 [2.74443626e-03 3.63159180e-03 9.50610638e-03]
 [1.45959854e-03 1.34799480e-02 6.45637512e-04]
 [5.43975830e-03 2.92778015e-

In [ ]:
# 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3]
tensor1 = tf.random.uniform(shape=[1, 224, 224, 3], minval=0, maxval=1)
print(tensor1)
print(tf.squeeze(tensor1))


tf.Tensor(
[[[[8.0315602e-01 4.9777734e-01 3.7054038e-01]
   [9.1186738e-01 6.3764203e-01 1.8209696e-01]
   [6.3791955e-01 2.7701473e-01 4.2271137e-02]
   ...
   [1.0830712e-01 4.5979273e-01 2.5716281e-01]
   [8.7138689e-01 1.8434000e-01 4.4757760e-01]
   [7.4110627e-02 9.0852141e-01 5.3693414e-01]]

  [[5.5596435e-01 6.8776274e-01 7.6051474e-02]
   [1.6737962e-01 7.1785092e-01 2.7642274e-01]
   [2.6995218e-01 3.2203627e-01 8.8224900e-01]
   ...
   [4.8168826e-01 5.0150025e-01 8.6756039e-01]
   [4.1261053e-01 1.2770486e-01 5.8186901e-01]
   [2.5495613e-01 3.9036548e-01 9.8529553e-01]]

  [[8.0935180e-01 1.9740558e-01 3.5899937e-01]
   [1.1216915e-01 9.1016293e-04 3.6382091e-01]
   [5.1202202e-01 3.9188230e-01 8.8335538e-01]
   ...
   [2.0133841e-01 9.1663551e-01 1.9890130e-01]
   [8.0388057e-01 3.9227080e-01 2.9688942e-01]
   [8.9319050e-01 2.9692888e-01 2.6492047e-01]]

  ...

  [[7.3653197e-01 5.9242892e-01 8.1022096e-01]
   [3.2385099e-01 9.4225824e-01 8.4279275e-01]
   [5.2548873e-

In [ ]:
# 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
tensor1 = tf.Variable([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tf.argmax(tensor1)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

In [ ]:
# 10. One-hot encode the tensor you created in 9
tf.one_hot(tensor1, 10)


<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Trying a new API (tf.summary)
writer = tf.summary.create_file_writer("/tmp/mylogs")
with writer.as_default():
  for step in range(100):
    # other model code would go here
    tf.summary.scalar("my_metric", 0.5, step=step)
    writer.flush()
writer

In [ ]:
# Creating tensors for a bill
tensor = tf.Variable([[20., 3., 50.],
                     [70., 32., 56.],
                     [3., 12., 40.],
                      [2., 32., 45.]])
print(f"My bill for this month is: {tf.reduce_sum(tensor)}\nAnd for the year is: {tf.reduce_sum(tensor * 12)}")

My bill for this month is: 365.0
And for the year is: 4380.0


### Go through tensorflow2 quickstart for beginners

### Load a dataset

In [ ]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

### Build a machine learning model

In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.4965537 ,  0.00359851,  0.2802872 ,  0.5352049 , -0.02380387,
        -0.07239889, -0.13487822, -0.1146393 , -0.11549064,  0.06245585]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.14533202, 0.08877151, 0.11706795, 0.15105926, 0.08637198,
        0.08227509, 0.07729188, 0.07887214, 0.07880501, 0.0941532 ]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

2.4976869

In [ ]:
model.compile(optimizer="adam",
              loss=loss_fn,
              metrics=["accuracy"])

In [ ]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2975 - accuracy: 0.9126
Epoch 2/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1452 - accuracy: 0.9564
Epoch 3/10
 923/1875 [=============>................] - ETA: 2s - loss: 0.1099 - accuracy: 0.9674

KeyboardInterrupt: ignored

In [ ]:
model.evaluate(x_test, y_test, verbose=2)

In [ ]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])